# Chi-Square Test for Independence

This notebook demonstrates how to perform a Chi-square test of independence to determine if there's a statistically significant relationship between two categorical variables.

## Import Required Libraries

We need numpy for numerical operations, seaborn for dataset loading, scipy.stats for chi-square test functions, and pandas for data manipulation and contingency table creation.

In [1]:
# Import required libraries for statistical analysis
import numpy as np  # For numerical operations and array manipulation
import seaborn as sns  # For loading built-in datasets
from scipy.stats import chi2_contingency  # For chi-square test functions
import pandas as pd  # For data manipulation and contingency table creation

## Load Dataset

We'll use the famous Titanic dataset from seaborn to analyze the relationship between gender and survival. This dataset contains information about passengers on the Titanic, including their demographics and survival status.

**Variables of Interest:**
- **sex**: Gender of the passenger (male/female)
- **survived**: Survival status (0 = died, 1 = survived)

This represents a classic case where we want to test if gender was associated with survival chances.

In [2]:
# Load the Titanic dataset from seaborn's built-in datasets
df = sns.load_dataset('titanic')  # Contains passenger demographics and survival data

## Explore the Dataset

Let's examine the structure of our dataset to understand the variables we're working with. The Titanic dataset contains 891 passengers with information about their demographics, ticket class, fare, and survival status.

In [3]:
# Display the first few rows of the dataset to understand its structure
df  # Shows passenger demographics and survival information

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

## Create Contingency Table

A contingency table (also called a cross-tabulation table) shows the frequency distribution of variables across categories. This is the foundation for the chi-square test.

**Purpose:**
- Organizes categorical data into a matrix format
- Shows observed frequencies for each combination of categories
- Required input for chi-square test calculations

For our analysis, we'll create a table showing survival counts by gender.

In [4]:
# Create contingency table (cross-tabulation) of sex vs survived
contingency_table = pd.crosstab(df['sex'], df['survived'])  # Shows frequency counts for each gender-survival combination

## View the Contingency Table

Let's examine our contingency table to see the observed frequencies:
- **Rows**: Gender categories (female, male)
- **Columns**: Survival status (0 = died, 1 = survived)
- **Values**: Count of passengers in each category combination

In [5]:
# Display the contingency table to observe the frequency distribution
contingency_table  # Shows observed counts for each gender-survival combination

survived    0    1
sex
female     81  233
male      468  109

## Perform Chi-Square Test

Now we perform the chi-square test of independence using scipy's `chi2_contingency` function. This function returns:
- **chi2**: The chi-square test statistic
- **p-value**: Probability of observing such a distribution by chance if variables are independent
- **dof**: Degrees of freedom (calculated as (rows-1) × (columns-1))
- **expected**: Expected frequencies under the null hypothesis of independence

**Null Hypothesis (H0)**: Gender and survival are independent (no relationship)
**Alternative Hypothesis (H1)**: Gender and survival are related (significant relationship)

In [6]:
# Perform chi-square test of independence on the contingency table
chi2, p_value, dof, expected = chi2_contingency(contingency_table)  # Returns test statistic, p-value, degrees of freedom, and expected frequencies

## View Expected Frequencies

The expected frequencies table shows what we would expect to see if gender and survival were truly independent (null hypothesis is true). This is calculated based on the marginal totals of the contingency table.

In [7]:
# Display the expected frequencies under null hypothesis of independence
expected  # Shows what counts we'd expect if gender and survival were unrelated

array([[193.47474747, 120.52525253],
       [355.52525253, 221.47474747]])

## View Chi-Square Statistic

The chi-square statistic measures the difference between observed and expected frequencies. A larger value suggests a greater deviation from what we'd expect under independence, indicating a potential relationship between variables.

In [8]:
# Display the calculated chi-square test statistic
chi2  # Shows the magnitude of difference between observed and expected frequencies

np.float64(260.71702016732104)

## Set Significance Level

The significance level (alpha) represents our threshold for determining statistical significance. A common choice is 0.05, meaning we're willing to accept a 5% chance of making a Type I error (rejecting a true null hypothesis).

In [9]:
# Set significance level for hypothesis testing
alpha = 0.05  # 5% significance level (common threshold for statistical significance)

## Make Statistical Decision

Now we compare our p-value to the significance level (alpha = 0.05) to make a decision:

- **If p-value < alpha**: Reject the null hypothesis (strong evidence of relationship between gender and survival)
- **If p-value >= alpha**: Fail to reject the null hypothesis (insufficient evidence of relationship)

**Interpretation:**
- Rejecting H0 suggests gender was significantly associated with survival chances
- Failing to reject H0 suggests no significant association between gender and survival

In [10]:
# Make statistical decision based on p-value comparison with significance level
if p_value < alpha:
    print("we reject the null hypothesis and there is a significant relationship between gender and survivl")
else:
    print("there is no connenction")  # Insufficient evidence of relationship between gender and survival

we reject the null hypothesis and there is a significant relationship between gender and survivl

## Interpretation of Results

Based on our chi-square test analysis:
- **Chi-square statistic**: Measures the deviation between observed and expected frequencies
- **P-value**: Probability of observing such a distribution by chance if variables are independent
- **Decision**: Based on comparison with significance level (alpha = 0.05)

## Key Concepts Summary

1. **Chi-Square Test of Independence**: Tests if two categorical variables are related
2. **Contingency Table**: Cross-tabulation showing observed frequencies
3. **Expected Frequencies**: What we'd expect if variables were independent
4. **Degrees of Freedom**: (rows-1) × (columns-1) for independence tests
5. **P-value Interpretation**: Probability under null hypothesis

## When to Use Chi-Square Test:
- Testing relationship between two categorical variables
- Sample size is sufficiently large (expected frequencies ≥ 5)
- Data consists of counts or frequencies
- Variables are nominal or ordinal

## Practical Applications:
- Market research (customer preferences vs demographics)
- Medical research (treatment vs outcomes)
- Social sciences (education level vs income category)
- Quality control (defect types vs production shifts)

## Assumptions:
- Random sampling
- Independent observations
- Mutually exclusive categories
- Sufficient sample size

In [11]:
import numpy as np 
import seaborn as sns 
from scipy.stats import chi2_contingency
import pandas as pd

In [12]:
df = sns.load_dataset('titanic')

In [13]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [14]:
contingency_table = pd.crosstab(df['sex'],df['survived'])

In [15]:
contingency_table

survived    0    1
sex
female     81  233
male      468  109

In [16]:
chi2, p_value , dof , expected = chi2_contingency(contingency_table)

In [17]:
expected

array([[193.47474747, 120.52525253],
       [355.52525253, 221.47474747]])

In [18]:
chi2

np.float64(260.71702016732104)

In [19]:
alpha = 0.05

In [20]:
if p_value < alpha:
    print("we reject the null hypothesis and there is a significant relationship between gender and survivl")
else:
    print("there is no connenction")

we reject the null hypothesis and there is a significant relationship between gender and survivl