In [15]:
import numpy as np 
import pandas as pd

# DataFrames Basic Operations

## Overview
This section covers fundamental operations for understanding and exploring DataFrame structures in Pandas. These operations are essential for data analysis and manipulation.

## Key Operations Covered:
- **Shape & Structure** - Understanding DataFrame dimensions
- **Column Information** - Accessing column names and data types
- **Statistical Summary** - Getting descriptive statistics
- **Basic Arithmetic** - Performing mathematical operations on columns

In [16]:
# Create a sample DataFrame for demonstration
# This DataFrame contains 3 columns (A, B, C) with 5 rows each
# Column A: Sequence from 1 to 5
# Column B: Multiples of 10 (10, 20, 30, 40, 50)
# Column C: Multiples of 100 (100, 200, 300, 400, 500)

df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [17]:
# Display the complete DataFrame
# This shows all rows and columns of our sample data

df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [18]:
# Check the shape of the DataFrame
# Returns a tuple: (number_of_rows, number_of_columns)
# Output: (5, 3) means 5 rows and 3 columns

df1.shape

(5, 3)

In [19]:
# Get the column names of the DataFrame
# Returns an Index object containing all column labels
# Useful for iterating over columns or checking column existence

df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [20]:
# Get detailed information about the DataFrame
# Provides:
# - Number of entries (rows)
# - Column names and non-null counts
# - Data types (dtypes) for each column
# - Memory usage of the DataFrame
# Essential for data quality checks and understanding data structure

df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [21]:
# Generate descriptive statistics for numerical columns
# Provides key statistical measures:
# - count: Number of non-null values
# - mean: Average value
# - std: Standard deviation (measure of spread)
# - min: Minimum value
# - 25%: First quartile (25th percentile)
# - 50%: Median (50th percentile)
# - 75%: Third quartile (75th percentile)
# - max: Maximum value
# Essential for understanding data distribution and identifying outliers

df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [22]:
# Perform arithmetic operations on DataFrame columns
# This adds 10 to each value in column 'A'
# Pandas supports element-wise operations on columns
# Result is a new Series with the computed values

df1['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [23]:
# Note: The previous operation (df1['A'] + 10) only displayed the result
# It did NOT modify the original DataFrame
# To permanently change the DataFrame, you would need:
# df1['A'] = df1['A'] + 10  # This would modify the original column

# Let's verify the original DataFrame is unchanged
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

# DataFrames Applying Functions

## Overview
This section demonstrates how to apply custom functions to DataFrame columns using the `.apply()` method. This is a powerful technique for data transformation and feature engineering.

## Key Concepts:
- **apply() method** - Apply functions along DataFrame axes
- **Lambda functions** - Anonymous functions for quick operations
- **Column creation** - Adding new columns based on existing data
- **Element-wise operations** - Performing calculations on each element

In [24]:
# Display the current DataFrame before applying functions
# We'll use this DataFrame to demonstrate the apply() method

df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [25]:
# Create a new column 'D' by applying a function to column 'B'
# 
# Explanation of the operation:
# - df1["B"] - Select column 'B'
# - .apply() - Apply a function to each element in the column
# - lambda x : x**2 - Anonymous function that squares the input (x)
# - df1['D'] = ... - Create new column 'D' with the results
#
# Result: Column 'D' contains the squared values of column 'B'
# [10², 20², 30², 40², 50²] = [100, 400, 900, 1600, 2500]

df1['D'] = df1["B"].apply(lambda x : x**2)

In [26]:
# Display the DataFrame after adding the new column 'D'
# Notice that column 'D' has been added with the squared values from column 'B'

df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500

In [27]:
# Additional Examples of Apply Functions

# Example 1: Apply a more complex lambda function
# Create a new column 'E' that categorizes values in column 'A'
df1['E'] = df1['A'].apply(lambda x: 'Small' if x <= 2 else 'Medium' if x <= 4 else 'Large')

# Example 2: Apply a regular function (not lambda)
def categorize_value(x):
    if x < 200:
        return 'Low'
    elif x < 400:
        return 'Medium'
    else:
        return 'High'

df1['F'] = df1['D'].apply(categorize_value)

# Example 3: Apply function to multiple columns
df1['G'] = df1.apply(lambda row: row['A'] + row['B'], axis=1)

print("DataFrame with multiple applied functions:")
print(df1)

DataFrame with multiple applied functions:
   A   B    C     D       E     F   G
0  1  10  100   100   Small   Low  11
1  2  20  200   400   Small  High  22
2  3  30  300   900  Medium  High  33
3  4  40  400  1600  Medium  High  44
4  5  50  500  2500   Large  High  55

In [ ]:
# Summary of DataFrame Operations

## Key Takeaways:

### 1. Basic Information Methods:
#- **df.shape** - Get dimensions (rows, columns)
#- **df.columns** - Get column names
#- **df.info()** - Get detailed DataFrame information
#- **df.describe()** - Get statistical summary

### 2. Column Operations:
#- **df['column']** - Select a single column
#- **df['column'] + 10** - Perform arithmetic on columns
#- **df['new_column'] = ...** - Create new columns

### 3. Apply Functions:
#- **df['column'].apply(function)** - Apply function to each element
#- **lambda x: expression** - Create anonymous functions
#- **axis=1** - Apply function to rows instead of columns

### 4. Common Use Cases:
#- **Data Transformation** - Convert, normalize, or scale data
#- **Feature Engineering** - Create new features from existing data
#- **Data Cleaning** - Apply cleaning functions to fix data issues
#- **Conditional Logic** - Apply if-else logic to create categories

### 5. Performance Tips:
#- Use vectorized operations when possible (df['A'] * 2)
#- Use apply() for complex operations that can't be vectorized
#- Consider using .map() for simple value substitutions
#- Use .apply() with axis=1 for row-wise operations

#These operations form the foundation of data manipulation in Pandas and are essential for data analysis workflows!

SyntaxError: unterminated string literal (detected at line 29) (2518336450.py, line 29)