In [22]:
import numpy as np 
import pandas as pd

In [23]:
df = pd.read_csv("Countries.csv")

In [24]:
df

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.000000,65.000000,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.000000,20.000000,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.500000,1.500000,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.26050,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.00000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.06020,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.56600,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [25]:
df.shape

(194, 64)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 64 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   country                                  194 non-null    object
 1   country_long                             194 non-null    object
 2   currency                                 194 non-null    object
 3   capital_city                             194 non-null    object
 4   region                                   194 non-null    object
 5   continent                                194 non-null    object
 6   demonym                                  194 non-null    object
 7   latitude                                 194 non-null    float64
 8   longitude                                194 non-null    float64
 9   agricultural_land                        193 non-null    float64
 10  forest_area                              194 non-null    float64
 11  land_area                                194 non-null    float64
 12  rural_land                               194 non-null    float64
 13  urban_land                               194 non-null    float64
 14  central_government_debt_pct_gdp          120 non-null    float64
 15  expense_pct_gdp                          156 non-null    float64
 16  gdp                                      193 non-null    float64
 17  inflation                                184 non-null    float64
 18  self_employed_pct                        179 non-null    float64
 19  tax_revenue_pct_gdp                      159 non-null    float64
 20  unemployment_pct                         179 non-null    float64
 21  vulnerable_employment_pct                179 non-null    float64
 22  electricity_access_pct                   194 non-null    float64
 23  alternative_nuclear_energy_pct           138 non-null    float64
 24  electricty_production_coal_pct           138 non-null    float64
 25  electricty_production_hydroelectric_pct  138 non-null    float64
 26  electricty_production_gas_pct            138 non-null    float64
 27  electricty_production_nuclear_pct        138 non-null    float64
 28  electricty_production_oil_pct            138 non-null    float64
 29  electricty_production_renewable_pct      138 non-null    float64
 30  energy_imports_pct                       138 non-null    float64
 31  fossil_energy_consumption_pct            168 non-null    float64
 32  renewable_energy_consumption_pct         192 non-null    float64
 33  co2_emissions                            191 non-null    float64
 34  methane_emissions                        191 non-null    float64
 35  nitrous_oxide_emissions                  191 non-null    float64
 36  greenhouse_other_emissions               184 non-null    float64
 37  urban_population_under_5m                194 non-null    float64
 38  health_expenditure_pct_gdp               190 non-null    float64
 39  health_expenditure_capita                190 non-null    float64
 40  hospital_beds                            192 non-null    float64
 41  hiv_incidence                            133 non-null    float64
 42  suicide_rate                             183 non-null    float64
 43  armed_forces                             174 non-null    float64
 44  internally_displaced_persons             73 non-null     float64
 45  military_expenditure_pct_gdp             163 non-null    float64
 46  birth_rate                               194 non-null    float64
 47  death_rate                               194 non-null    float64
 48  fertility_rate                           193 non-null    float64
 49  internet_pct                             194 non-null    float64
 50  life_expectancy                          191 non-null    float64
 51  net_migration                            194 non-null    int64
 52  population_female                        194 non-null    int64
 53  population_male                          194 non-null    int64
 54  population                               194 non-null    int64
 55  women_parliament_seats_pct               193 non-null    float64
 56  rural_population                         194 non-null    int64
 57  urban_population                         194 non-null    int64
 58  press                                    194 non-null    float64
 59  democracy_score                          194 non-null    float64
 60  democracy_type                           194 non-null    object
 61  median_age                               194 non-null    float64
 62  political_leader                         187 non-null    object
 63  title                                    187 non-null    object
dtypes: float64(48), int64(6), object(10)
memory usage: 97.1+ KB

In [27]:
df.describe()

,latitude,longitude,agricultural_land,forest_area,land_area,rural_land,urban_land,central_government_debt_pct_gdp,expense_pct_gdp,gdp,...,net_migration,population_female,population_male,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,median_age
count,194.000000,194.000000,1.930000e+02,1.940000e+02,1.940000e+02,1.940000e+02,194.000000,120.000000,156.000000,1.930000e+02,...,194.000000,1.940000e+02,1.940000e+02,1.940000e+02,193.000000,1.940000e+02,1.940000e+02,194.000000,194.000000,194.000000
mean,18.975601,22.027491,2.454551e+05,2.086784e+05,6.675087e+05,6.563711e+05,9777.116531,66.759366,30.051403,5.144851e+11,...,-51.407216,2.028316e+07,2.050572e+07,4.078888e+07,25.022994,1.763322e+07,2.315566e+07,2.539330,4.644536,25.661856
std,23.876225,66.396389,6.356268e+05,7.824926e+05,1.837107e+06,1.811169e+06,42301.458421,71.806247,26.740880,2.307148e+12,...,94525.968598,7.258941e+07,7.607158e+07,1.486470e+08,12.671044,7.664187e+07,7.940393e+07,1.800128,2.818297,9.415569
min,-41.000000,-175.000000,4.000000e+00,0.000000e+00,2.027000e+00,3.495450e-02,0.000000,0.000000,0.000267,6.034940e+07,...,-525116.000000,5.513000e+03,5.799000e+03,1.131200e+04,0.000000,0.000000e+00,5.717000e+03,0.000000,0.000000,10.500000
25%,4.000000,-5.000000,6.464000e+03,3.331775e+03,2.355250e+04,2.186562e+04,359.618250,31.951300,18.371875,1.181390e+10,...,-12242.250000,1.036218e+06,1.044902e+06,2.106358e+06,15.384600,5.896640e+05,1.222244e+06,1.525000,2.722500,16.950000
50%,16.583333,21.500000,3.872780e+04,2.528925e+04,1.203750e+05,1.159945e+05,1645.170000,55.426850,27.337750,4.115390e+10,...,-970.000000,4.502713e+06,4.450049e+06,9.125614e+06,25.252500,2.512382e+06,4.508837e+06,2.400000,5.050000,24.950000
75%,40.000000,50.162500,2.150000e+05,1.236735e+05,5.237000e+05,4.911505e+05,4054.022500,79.539300,35.083500,2.519450e+11,...,2904.250000,1.526606e+07,1.478872e+07,3.031361e+07,33.636400,1.133354e+07,1.621355e+07,2.925000,6.967500,34.050000
max,65.000000,178.000000,5.285080e+06,8.153120e+06,1.637690e+07,1.622420e+07,522345.000000,687.994000,310.443000,2.546270e+13,...,561580.000000,6.915285e+08,7.311805e+08,1.417173e+09,61.250000,9.088048e+08,8.975784e+08,10.000000,9.870000,50.500000

In [28]:
#which country has the highest population
df[df['population'] == df['population'].max()]['country']

75    India
Name: country, dtype: object

In [29]:
df.columns

Index(['country', 'country_long', 'currency', 'capital_city', 'region',
       'continent', 'demonym', 'latitude', 'longitude', 'agricultural_land',
       'forest_area', 'land_area', 'rural_land', 'urban_land',
       'central_government_debt_pct_gdp', 'expense_pct_gdp', 'gdp',
       'inflation', 'self_employed_pct', 'tax_revenue_pct_gdp',
       'unemployment_pct', 'vulnerable_employment_pct',
       'electricity_access_pct', 'alternative_nuclear_energy_pct',
       'electricty_production_coal_pct',
       'electricty_production_hydroelectric_pct',
       'electricty_production_gas_pct', 'electricty_production_nuclear_pct',
       'electricty_production_oil_pct', 'electricty_production_renewable_pct',
       'energy_imports_pct', 'fossil_energy_consumption_pct',
       'renewable_energy_consumption_pct', 'co2_emissions',
       'methane_emissions', 'nitrous_oxide_emissions',
       'greenhouse_other_emissions', 'urban_population_under_5m',
       'health_expenditure_pct_gdp', 'health_expenditure_capita',
       'hospital_beds', 'hiv_incidence', 'suicide_rate', 'armed_forces',
       'internally_displaced_persons', 'military_expenditure_pct_gdp',
       'birth_rate', 'death_rate', 'fertility_rate', 'internet_pct',
       'life_expectancy', 'net_migration', 'population_female',
       'population_male', 'population', 'women_parliament_seats_pct',
       'rural_population', 'urban_population', 'press', 'democracy_score',
       'democracy_type', 'median_age', 'political_leader', 'title'],
      dtype='object')

In [30]:
#what is the capital of the country with highest population
df[df['population'] == df['population'].max()]['capital_city']

75    New Delhi
Name: capital_city, dtype: object

In [31]:
#which country has the least population
df[df['population'] == df['population'].min()]['country']

179    Tuvalu
Name: country, dtype: object

In [32]:
#what is the capital of the country with least population
df[df['population'] == df['population'].min()]['capital_city']

179    Funafuti
Name: capital_city, dtype: object

In [33]:
df.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.0,65.0,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.0,20.0,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.0,3.0,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.5,1.5,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.5,18.5,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President

In [34]:
#give me top 5 countries with highest democratic score
df.sort_values(by = 'democracy_score',ascending=False,inplace = True)

In [35]:
df['country'].head()

127         Norway
74         Iceland
164         Sweden
122    New Zealand
46         Denmark
Name: country, dtype: object

In [36]:
#how many total regions are there
df['region'].value_counts().count()

np.int64(22)

In [37]:
#how many countries lie in Eastern Europe region
df[df['region'] == "Eastern Europe"][ 'country']

43      Czech Republic
151    Slovak Republic
24            Bulgaria
136             Poland
73             Hungary
139            Romania
111            Moldova
181            Ukraine
14             Belarus
140             Russia
Name: country, dtype: object

In [38]:
#who is the political leader of the 2nd highest populated country
df[df['population'] == df['population'].nlargest(2).iloc[1]]['political_leader']

34    Xi Jinping
Name: political_leader, dtype: object

In [39]:
# how many countries are there whoes political leaders are unknown
df[df['political_leader'].isna()]['country'].count()

np.int64(7)

In [40]:
#how many country have Republic in their full name
count = 0
def counting(txt):
    global count 
    if 'republic' in txt.lower():
        count+= 1
    return txt
df['country_long'] = df['country_long'].apply(counting)
print(count)

125

In [41]:
#which country in african region has highest population
africa_df = df[df['continent'] == 'Africa']

In [42]:
africa_df[africa_df['population'] == africa_df['population'].max()]['country']

125    Nigeria
Name: country, dtype: object

In [43]:
# Advanced Data Extraction and Feature Engineering

# Let's extract more meaningful features from the countries dataset
# We'll create economic indicators, development metrics, and geographical features

In [44]:
# Create economic indicators and development metrics

# GDP per capita
df['gdp_per_capita'] = df['gdp'] / df['population']

# Population density (people per square km)
df['population_density'] = df['population'] / df['land_area']

# Urbanization rate
df['urbanization_rate'] = (df['urban_population'] / df['population']) * 100

# Gender balance ratio (female to male ratio)
df['gender_ratio'] = df['population_female'] / df['population_male']

# Dependency ratio (assuming working age 15-64, but using median age as proxy)
df['dependency_ratio_proxy'] = (df['population'] - (df['median_age'] * df['population'] / 25)) / (df['median_age'] * df['population'] / 25)

print("Economic and Demographic Indicators Created:")
print(f"GDP per capita range: ${df['gdp_per_capita'].min():,.0f} - ${df['gdp_per_capita'].max():,.0f}")
print(f"Population density range: {df['population_density'].min():.1f} - {df['population_density'].max():.1f} people/km²")
print(f"Urbanization rate range: {df['urbanization_rate'].min():.1f}% - {df['urbanization_rate'].max():.1f}%")

Economic and Demographic Indicators Created:
GDP per capita range: $238 - $235,711
Population density range: 2.2 - 17991.6 people/km²
Urbanization rate range: 13.6% - 100.0%

In [45]:
# Create health and development indices

# Health Expenditure per capita
df['health_expenditure_per_capita'] = (df['health_expenditure_pct_gdp'] / 100) * df['gdp_per_capita']

# Hospital beds per 1000 people
df['hospital_beds_per_1000'] = (df['hospital_beds'] / df['population']) * 1000

# Internet penetration score (0-100 scale)
df['internet_score'] = df['internet_pct']

# Press freedom score (inverted - higher is better)
df['press_freedom_score'] = 10 - df['press']

# Life expectancy score (normalized 0-100)
df['life_expectancy_score'] = (df['life_expectancy'] / 85) * 100

# Women's representation score
df['women_representation_score'] = df['women_parliament_seats_pct']

print("Health and Development Indices Created:")
print(f"Health expenditure per capita range: ${df['health_expenditure_per_capita'].min():.0f} - ${df['health_expenditure_per_capita'].max():.0f}")
print(f"Hospital beds per 1000 range: {df['hospital_beds_per_1000'].min():.1f} - {df['hospital_beds_per_1000'].max():.1f}")
print(f"Life expectancy score range: {df['life_expectancy_score'].min():.1f} - {df['life_expectancy_score'].max():.1f}")

Health and Development Indices Created:
Health expenditure per capita range: $15 - $14375
Hospital beds per 1000 range: 0.0 - 0.5
Life expectancy score range: 62.4 - 98.8

In [46]:
# Create environmental and energy metrics

# CO2 emissions per capita
df['co2_per_capita'] = df['co2_emissions'] / df['population']

# CO2 intensity (CO2 per GDP)
df['co2_intensity'] = df['co2_emissions'] / df['gdp']

# Renewable energy adoption score
df['renewable_energy_score'] = df['renewable_energy_consumption_pct']

# Energy self-sufficiency (inverse of imports)
df['energy_self_sufficiency'] = 100 - df['energy_imports_pct']

# Environmental impact score (combination of emissions and renewable energy)
df['environmental_score'] = (df['renewable_energy_score'] * 0.6) + ((100 - df['co2_per_capita'] / df['co2_per_capita'].max() * 100) * 0.4)

print("Environmental Metrics Created:")
print(f"CO2 per capita range: {df['co2_per_capita'].min():.2f} - {df['co2_per_capita'].max():.2f}")
print(f"CO2 intensity range: {df['co2_intensity'].min():.6f} - {df['co2_intensity'].max():.6f}")
print(f"Environmental score range: {df['environmental_score'].min():.1f} - {df['environmental_score'].max():.1f}")

Environmental Metrics Created:
CO2 per capita range: 0.00 - 0.03
CO2 intensity range: 0.000000 - 0.000002
Environmental score range: 0.0 - 97.7

In [47]:
# Create geographical and regional features

# Hemisphere classification
def classify_hemisphere(lat):
    if lat > 0:
        return 'Northern'
    elif lat < 0:
        return 'Southern'
    else:
        return 'Equatorial'

df['hemisphere'] = df['latitude'].apply(classify_hemisphere)

# Climate zone based on latitude
def classify_climate_zone(lat):
    abs_lat = abs(lat)
    if abs_lat < 23.5:
        return 'Tropical'
    elif abs_lat < 40:
        return 'Subtropical'
    elif abs_lat < 60:
        return 'Temperate'
    else:
        return 'Polar'

df['climate_zone'] = df['latitude'].apply(classify_climate_zone)

# Distance from equator
df['distance_from_equator'] = abs(df['latitude'])

# Region size (number of countries per region)
region_counts = df['region'].value_counts()
df['region_size'] = df['region'].map(region_counts)

print("Geographical Features Created:")
print(f"Hemispheres: {df['hemisphere'].value_counts().to_dict()}")
print(f"Climate zones: {df['climate_zone'].value_counts().to_dict()}")
print(f"Region sizes range: {df['region_size'].min()} - {df['region_size'].max()} countries")

Geographical Features Created:
Hemispheres: {'Northern': 154, 'Southern': 39, 'Equatorial': 1}
Climate zones: {'Tropical': 103, 'Temperate': 45, 'Subtropical': 40, 'Polar': 6}
Region sizes range: 2 - 17 countries

In [48]:
# Create development and governance indices

# Human Development Index (simplified version)
# Components: life expectancy, education (internet proxy), income (GDP per capita)
df['life_exp_normalized'] = df['life_expectancy'] / 85
df['education_normalized'] = df['internet_pct'] / 100
df['income_normalized'] = np.log(df['gdp_per_capita']) / np.log(df['gdp_per_capita'].max())
df['simplified_hdi'] = (df['life_exp_normalized'] + df['education_normalized'] + df['income_normalized']) / 3

# Development level classification
def classify_development(hdi):
    if hdi >= 0.8:
        return 'Very High'
    elif hdi >= 0.7:
        return 'High'
    elif hdi >= 0.55:
        return 'Medium'
    else:
        return 'Low'

df['development_level'] = df['simplified_hdi'].apply(classify_development)

# Governance score (democracy + press freedom)
df['governance_score'] = (df['democracy_score'] / 10) * 0.7 + (df['press_freedom_score'] / 10) * 0.3

# Economic stability score (inverse of inflation + debt management)
df['economic_stability'] = ((100 - df['inflation']) / 100) * 0.6 + ((100 - df['central_government_debt_pct_gdp']) / 100) * 0.4

print("Development Indices Created:")
print(f"HDI range: {df['simplified_hdi'].min():.3f} - {df['simplified_hdi'].max():.3f}")
print(f"Development levels: {df['development_level'].value_counts().to_dict()}")
print(f"Governance score range: {df['governance_score'].min():.3f} - {df['governance_score'].max():.3f}")

Development Indices Created:
HDI range: 0.388 - 0.974
Development levels: {'Very High': 75, 'High': 45, 'Medium': 37, 'Low': 37}
Governance score range: 0.172 - 0.811

In [49]:
# Create composite rankings and scores

# Overall Development Score (weighted combination)
df['overall_development_score'] = (
    df['simplified_hdi'] * 0.3 +
    df['governance_score'] * 0.2 +
    df['economic_stability'] * 0.2 +
    df['environmental_score'] / 100 * 0.15 +
    df['internet_score'] / 100 * 0.15
)

# Quality of Life Index
df['quality_of_life_index'] = (
    df['life_expectancy_score'] / 100 * 0.3 +
    df['internet_score'] / 100 * 0.2 +
    df['press_freedom_score'] / 10 * 0.2 +
    df['women_representation_score'] / 50 * 0.15 +
    df['health_expenditure_per_capita'] / df['health_expenditure_per_capita'].max() * 0.15
)

# Economic Power Index
df['economic_power_index'] = (
    df['gdp'] / df['gdp'].max() * 0.4 +
    df['gdp_per_capita'] / df['gdp_per_capita'].max() * 0.3 +
    (100 - df['unemployment_pct']) / 100 * 0.2 +
    (100 - df['inflation']) / 100 * 0.1
)

print("Composite Indices Created:")
print(f"Overall Development Score range: {df['overall_development_score'].min():.3f} - {df['overall_development_score'].max():.3f}")
print(f"Quality of Life Index range: {df['quality_of_life_index'].min():.3f} - {df['quality_of_life_index'].max():.3f}")
print(f"Economic Power Index range: {df['economic_power_index'].min():.3f} - {df['economic_power_index'].max():.3f}")

Composite Indices Created:
Overall Development Score range: 0.226 - 0.848
Quality of Life Index range: 0.418 - 0.827
Economic Power Index range: 0.064 - 0.782

In [50]:
# Display enhanced dataset with all extracted features
print("Enhanced Dataset Overview:")
print(f"Original columns: 64")
print(f"Enhanced columns: {len(df.columns)}")
print(f"New features added: {len(df.columns) - 64}")

print("\nNew Features Added:")
new_features = [col for col in df.columns if col not in [
    'country', 'country_long', 'currency', 'capital_city', 'region', 'continent', 
    'demonym', 'latitude', 'longitude', 'agricultural_land', 'forest_area', 
    'land_area', 'rural_land', 'urban_land', 'central_government_debt_pct_gdp', 
    'expense_pct_gdp', 'gdp', 'inflation', 'self_employed_pct', 'tax_revenue_pct_gdp',
    'unemployment_pct', 'vulnerable_employment_pct', 'electricity_access_pct',
    'alternative_nuclear_energy_pct', 'electricty_production_coal_pct',
    'electricty_production_hydroelectric_pct', 'electricty_production_gas_pct',
    'electricty_production_nuclear_pct', 'electricty_production_oil_pct',
    'electricty_production_renewable_pct', 'energy_imports_pct',
    'fossil_energy_consumption_pct', 'renewable_energy_consumption_pct',
    'co2_emissions', 'methane_emissions', 'nitrous_oxide_emissions',
    'greenhouse_other_emissions', 'urban_population_under_5m',
    'health_expenditure_pct_gdp', 'health_expenditure_capita', 'hospital_beds',
    'hiv_incidence', 'suicide_rate', 'armed_forces', 'internally_displaced_persons',
    'military_expenditure_pct_gdp', 'birth_rate', 'death_rate', 'fertility_rate',
    'internet_pct', 'life_expectancy', 'net_migration', 'population_female',
    'population_male', 'population', 'women_parliament_seats_pct',
    'rural_population', 'urban_population', 'press', 'democracy_score',
    'democracy_type', 'median_age', 'political_leader', 'title'
]]

for i, feature in enumerate(new_features, 1):
    print(f"{i:2d}. {feature}")

print(f"\nSample of Enhanced Dataset:")
df[['country', 'gdp_per_capita', 'population_density', 'simplified_hdi', 'overall_development_score']].head()

Enhanced Dataset Overview:
Original columns: 64
Enhanced columns: 94
New features added: 30

New Features Added:
 1. gdp_per_capita
 2. population_density
 3. urbanization_rate
 4. gender_ratio
 5. dependency_ratio_proxy
 6. health_expenditure_per_capita
 7. hospital_beds_per_1000
 8. internet_score
 9. press_freedom_score
10. life_expectancy_score
11. women_representation_score
12. co2_per_capita
13. co2_intensity
14. renewable_energy_score
15. energy_self_sufficiency
16. environmental_score
17. hemisphere
18. climate_zone
19. distance_from_equator
20. region_size
21. life_exp_normalized
22. education_normalized
23. income_normalized
24. simplified_hdi
25. development_level
26. governance_score
27. economic_stability
28. overall_development_score
29. quality_of_life_index
30. economic_power_index

Sample of Enhanced Dataset:

,country,gdp_per_capita,population_density,simplified_hdi,overall_development_score
127,Norway,106148.711584,14.980378,0.967327,0.848280
74,Iceland,72902.854150,3.787563,0.959493,0.839632
164,Sweden,55873.204588,25.748473,0.914393,0.805856
122,New Zealand,48249.253527,19.460332,0.931860,0.794496
46,Denmark,66983.147827,147.575925,0.946631,0.791576

In [51]:
# Advanced Analysis with Extracted Features

# Top countries by different development metrics
print("=== TOP COUNTRIES BY DEVELOPMENT METRICS ===\n")

# Highest HDI countries
print("🏆 TOP 5 COUNTRIES BY HUMAN DEVELOPMENT INDEX:")
top_hdi = df.nlargest(5, 'simplified_hdi')[['country', 'simplified_hdi', 'life_expectancy', 'internet_pct', 'gdp_per_capita']]
for i, (_, country) in enumerate(top_hdi.iterrows(), 1):
    print(f"{i}. {country['country']}: HDI {country['simplified_hdi']:.3f} (Life Exp: {country['life_expectancy']:.1f}, Internet: {country['internet_pct']:.1f}%, GDP/capita: ${country['gdp_per_capita']:,.0f})")

# Best quality of life
print(f"\n🌟 TOP 5 COUNTRIES BY QUALITY OF LIFE:")
top_quality = df.nlargest(5, 'quality_of_life_index')[['country', 'quality_of_life_index', 'life_expectancy_score', 'press_freedom_score', 'internet_score']]
for i, (_, country) in enumerate(top_quality.iterrows(), 1):
    print(f"{i}. {country['country']}: QLI {country['quality_of_life_index']:.3f} (Life Score: {country['life_expectancy_score']:.1f}, Press: {country['press_freedom_score']:.1f}, Internet: {country['internet_score']:.1f})")

# Most economically powerful
print(f"\n💰 TOP 5 COUNTRIES BY ECONOMIC POWER:")
top_economic = df.nlargest(5, 'economic_power_index')[['country', 'economic_power_index', 'gdp', 'gdp_per_capita', 'unemployment_pct']]
for i, (_, country) in enumerate(top_economic.iterrows(), 1):
    print(f"{i}. {country['country']}: EPI {country['economic_power_index']:.3f} (GDP: ${country['gdp']:,.0f}B, GDP/capita: ${country['gdp_per_capita']:,.0f}, Unemployment: {country['unemployment_pct']:.1f}%)")

=== TOP COUNTRIES BY DEVELOPMENT METRICS ===

🏆 TOP 5 COUNTRIES BY HUMAN DEVELOPMENT INDEX:
1. Liechtenstein: HDI 0.974 (Life Exp: 84.0, Internet: 95.6%, GDP/capita: $182,735)
2. Luxembourg: HDI 0.971 (Life Exp: 83.0, Internet: 98.7%, GDP/capita: $126,426)
3. Norway: HDI 0.967 (Life Exp: 83.0, Internet: 99.0%, GDP/capita: $106,149)
4. Iceland: HDI 0.959 (Life Exp: 83.0, Internet: 99.7%, GDP/capita: $72,903)
5. Switzerland: HDI 0.956 (Life Exp: 84.0, Internet: 95.6%, GDP/capita: $92,101)

🌟 TOP 5 COUNTRIES BY QUALITY OF LIFE:
1. United States: QLI 0.827 (Life Score: 89.4, Press: 7.0, Internet: 91.8)
2. United Arab Emirates: QLI 0.825 (Life Score: 92.9, Press: 8.2, Internet: 100.0)
3. Iceland: QLI 0.802 (Life Score: 97.6, Press: 4.7, Internet: 99.7)
4. Singapore: QLI 0.784 (Life Score: 97.6, Press: 8.5, Internet: 91.1)
5. Australia: QLI 0.778 (Life Score: 97.6, Press: 5.3, Internet: 96.2)

💰 TOP 5 COUNTRIES BY ECONOMIC POWER:
1. United States: EPI 0.782 (GDP: $25,462,700,000,000B, GDP/capita: $76,399, Unemployment: 3.6%)
2. China: EPI 0.587 (GDP: $17,963,200,000,000B, GDP/capita: $12,720, Unemployment: 4.9%)
3. Luxembourg: EPI 0.446 (GDP: $82,274,800,000B, GDP/capita: $126,426, Unemployment: 4.7%)
4. Norway: EPI 0.432 (GDP: $579,267,000,000B, GDP/capita: $106,149, Unemployment: 3.2%)
5. Ireland: EPI 0.424 (GDP: $529,245,000,000B, GDP/capita: $104,039, Unemployment: 4.4%)

In [52]:
# Regional and Continental Analysis

print("=== REGIONAL AND CONTINENTAL ANALYSIS ===\n")

# Average development by continent
print("📊 AVERAGE DEVELOPMENT BY CONTINENT:")
continent_analysis = df.groupby('continent').agg({
    'simplified_hdi': 'mean',
    'gdp_per_capita': 'mean',
    'life_expectancy': 'mean',
    'internet_pct': 'mean',
    'overall_development_score': 'mean'
}).round(3)
print(continent_analysis)

# Development levels by continent
print(f"\n🎯 DEVELOPMENT LEVELS BY CONTINENT:")
development_by_continent = pd.crosstab(df['continent'], df['development_level'], margins=True)
print(development_by_continent)

# Top countries in each continent
print(f"\n🌍 TOP COUNTRY IN EACH CONTINENT (by overall development score):")
for continent in df['continent'].unique():
    top_country = df[df['continent'] == continent].nlargest(1, 'overall_development_score').iloc[0]
    print(f"{continent}: {top_country['country']} (Score: {top_country['overall_development_score']:.3f})")

=== REGIONAL AND CONTINENTAL ANALYSIS ===

📊 AVERAGE DEVELOPMENT BY CONTINENT:
           simplified_hdi  gdp_per_capita  life_expectancy  internet_pct  \
continent
Africa              0.579        2637.351           62.833        39.836
Americas            0.786       14328.454           72.571        75.681
Asia                0.757       14639.276           73.213        69.138
Europe              0.873       44556.583           78.171        87.245
Oceania             0.720       12564.863           70.143        62.814

           overall_development_score
continent
Africa                         0.588
Americas                       0.691
Asia                           0.658
Europe                         0.725
Oceania                        0.632

🎯 DEVELOPMENT LEVELS BY CONTINENT:
development_level  High  Low  Medium  Very High  All
continent
Africa                8   29      15          2   54
Americas             14    0       5         16   35
Asia                 13    5      11         18   47
Europe                4    3       0         37   44
Oceania               6    0       6          2   14
All                  45   37      37         75  194

🌍 TOP COUNTRY IN EACH CONTINENT (by overall development score):
Europe: Norway (Score: 0.848)
Oceania: New Zealand (Score: 0.794)
Americas: Chile (Score: 0.801)
Africa: Botswana (Score: 0.729)
Asia: Korea (Score: 0.777)

In [53]:
# Environmental Performance Analysis

print("=== ENVIRONMENTAL PERFORMANCE ANALYSIS ===\n")

# Most environmentally friendly countries
print("🌱 TOP 5 MOST ENVIRONMENTALLY FRIENDLY COUNTRIES:")
top_enviro = df.nlargest(5, 'environmental_score')[['country', 'environmental_score', 'renewable_energy_score', 'co2_per_capita', 'co2_intensity']]
for i, (_, country) in enumerate(top_enviro.iterrows(), 1):
    print(f"{i}. {country['country']}: Env Score {country['environmental_score']:.1f} (Renewable: {country['renewable_energy_score']:.1f}%, CO2/capita: {country['co2_per_capita']:.2f})")

# CO2 emissions analysis
print(f"\n🏭 CO2 EMISSIONS ANALYSIS:")
print(f"Highest CO2 per capita: {df.loc[df['co2_per_capita'].idxmax(), 'country']} ({df['co2_per_capita'].max():.2f})")
print(f"Lowest CO2 per capita: {df.loc[df['co2_per_capita'].idxmin(), 'country']} ({df['co2_per_capita'].min():.2f})")
print(f"Average CO2 per capita: {df['co2_per_capita'].mean():.2f}")

# Renewable energy adoption
print(f"\n⚡ RENEWABLE ENERGY ADOPTION:")
print(f"Highest renewable energy: {df.loc[df['renewable_energy_score'].idxmax(), 'country']} ({df['renewable_energy_score'].max():.1f}%)")
print(f"Lowest renewable energy: {df.loc[df['renewable_energy_score'].idxmin(), 'country']} ({df['renewable_energy_score'].min():.1f}%)")
print(f"Average renewable energy: {df['renewable_energy_score'].mean():.1f}%")

# Environmental performance by continent
print(f"\n🌍 ENVIRONMENTAL PERFORMANCE BY CONTINENT:")
enviro_by_continent = df.groupby('continent')['environmental_score'].mean().sort_values(ascending=False)
for continent, score in enviro_by_continent.items():
    print(f"{continent}: {score:.1f}")

=== ENVIRONMENTAL PERFORMANCE ANALYSIS ===

🌱 TOP 5 MOST ENVIRONMENTALLY FRIENDLY COUNTRIES:
1. Dem. Rep. Congo: Env Score 97.7 (Renewable: 96.2%, CO2/capita: 0.00)
2. Somalia: Env Score 97.2 (Renewable: 95.4%, CO2/capita: 0.00)
3. Uganda: Env Score 95.7 (Renewable: 93.0%, CO2/capita: 0.00)
4. Liberia: Env Score 95.5 (Renewable: 92.9%, CO2/capita: 0.00)
5. Central African Republic: Env Score 94.2 (Renewable: 90.5%, CO2/capita: 0.00)

🏭 CO2 EMISSIONS ANALYSIS:
Highest CO2 per capita: Qatar (0.03)
Lowest CO2 per capita: Dem. Rep. Congo (0.00)
Average CO2 per capita: 0.00

⚡ RENEWABLE ENERGY ADOPTION:
Highest renewable energy: Dem. Rep. Congo (96.2%)
Lowest renewable energy: Bahrain (0.0%)
Average renewable energy: 32.1%

🌍 ENVIRONMENTAL PERFORMANCE BY CONTINENT:
Africa: 72.6
Americas: 50.8
Europe: 49.7
Oceania: 49.2
Asia: 42.9

In [54]:
# Demographic and Social Insights

print("=== DEMOGRAPHIC AND SOCIAL INSIGHTS ===\n")

# Population analysis
print("👥 POPULATION ANALYSIS:")
print(f"Most populous: {df.loc[df['population'].idxmax(), 'country']} ({df['population'].max():,.0f})")
print(f"Least populous: {df.loc[df['population'].idxmin(), 'country']} ({df['population'].min():,.0f})")
print(f"Highest population density: {df.loc[df['population_density'].idxmax(), 'country']} ({df['population_density'].max():.1f} people/km²)")
print(f"Lowest population density: {df.loc[df['population_density'].idxmin(), 'country']} ({df['population_density'].min():.1f} people/km²)")

# Age demographics
print(f"\n👵 AGE DEMOGRAPHICS:")
print(f"Oldest population: {df.loc[df['median_age'].idxmax(), 'country']} (Median age: {df['median_age'].max():.1f})")
print(f"Youngest population: {df.loc[df['median_age'].idxmin(), 'country']} (Median age: {df['median_age'].min():.1f})")
print(f"Average median age: {df['median_age'].mean():.1f}")

# Gender balance
print(f"\n⚖️ GENDER BALANCE:")
most_balanced = df.loc[(df['gender_ratio'] - 1).abs().idxmin(), 'country']
most_imbalanced = df.loc[(df['gender_ratio'] - 1).abs().idxmax(), 'country']
print(f"Most gender-balanced: {most_balanced} (Ratio: {df.loc[df['country'] == most_balanced, 'gender_ratio'].iloc[0]:.3f})")
print(f"Most gender-imbalanced: {most_imbalanced} (Ratio: {df.loc[df['country'] == most_imbalanced, 'gender_ratio'].iloc[0]:.3f})")

# Urbanization
print(f"\n🏙️ URBANIZATION:")
print(f"Most urbanized: {df.loc[df['urbanization_rate'].idxmax(), 'country']} ({df['urbanization_rate'].max():.1f}%)")
print(f"Least urbanized: {df.loc[df['urbanization_rate'].idxmin(), 'country']} ({df['urbanization_rate'].min():.1f}%)")
print(f"Average urbanization: {df['urbanization_rate'].mean():.1f}%")

=== DEMOGRAPHIC AND SOCIAL INSIGHTS ===

👥 POPULATION ANALYSIS:
Most populous: India (1,417,173,173)
Least populous: Tuvalu (11,312)
Highest population density: Monaco (17991.6 people/km²)
Lowest population density: Mongolia (2.2 people/km²)

👵 AGE DEMOGRAPHICS:
Oldest population: Monaco (Median age: 50.5)
Youngest population: Niger (Median age: 10.5)
Average median age: 25.7

⚖️ GENDER BALANCE:
Most gender-balanced: Grenada (Ratio: 1.000)
Most gender-imbalanced: Qatar (Ratio: 0.379)

🏙️ URBANIZATION:
Most urbanized: Singapore (100.0%)
Least urbanized: Papua New Guinea (13.6%)
Average urbanization: 60.0%

In [55]:
# Governance and Democracy Analysis

print("=== GOVERNANCE AND DEMOCRACY ANALYSIS ===\n")

# Democracy analysis
print("🗳️ DEMOCRACY ANALYSIS:")
print(f"Most democratic: {df.loc[df['democracy_score'].idxmax(), 'country']} (Score: {df['democracy_score'].max():.2f})")
print(f"Least democratic: {df.loc[df['democracy_score'].idxmin(), 'country']} (Score: {df['democracy_score'].min():.2f})")

# Democracy types distribution
print(f"\n📊 DEMOCRACY TYPES:")
democracy_types = df['democracy_type'].value_counts()
for dtype, count in democracy_types.items():
    print(f"{dtype}: {count} countries ({count/len(df)*100:.1f}%)")

# Press freedom
print(f"\n📰 PRESS FREEDOM:")
print(f"Freest press: {df.loc[df['press_freedom_score'].idxmax(), 'country']} (Score: {df['press_freedom_score'].max():.2f})")
print(f"Most restricted press: {df.loc[df['press_freedom_score'].idxmin(), 'country']} (Score: {df['press_freedom_score'].min():.2f})")

# Women's representation
print(f"\n👩 WOMEN'S POLITICAL REPRESENTATION:")
print(f"Highest representation: {df.loc[df['women_parliament_seats_pct'].idxmax(), 'country']} ({df['women_parliament_seats_pct'].max():.1f}%)")
print(f"Lowest representation: {df.loc[df['women_parliament_seats_pct'].idxmin(), 'country']} ({df['women_parliament_seats_pct'].min():.1f}%)")
print(f"Average representation: {df['women_parliament_seats_pct'].mean():.1f}%")

# Governance by continent
print(f"\n🌍 AVERAGE GOVERNANCE SCORE BY CONTINENT:")
governance_by_continent = df.groupby('continent')['governance_score'].mean().sort_values(ascending=False)
for continent, score in governance_by_continent.items():
    print(f"{continent}: {score:.3f}")

=== GOVERNANCE AND DEMOCRACY ANALYSIS ===

🗳️ DEMOCRACY ANALYSIS:
Most democratic: Norway (Score: 9.87)
Least democratic: Palau (Score: 0.00)

📊 DEMOCRACY TYPES:
Flawed democracy: 53 countries (27.3%)
Authoritarian: 53 countries (27.3%)
Hybrid regime: 39 countries (20.1%)
Unknown: 29 countries (14.9%)
Full democracy: 20 countries (10.3%)

📰 PRESS FREEDOM:
Freest press: Palau (Score: 10.00)
Most restricted press: Norway (Score: 0.00)

👩 WOMEN'S POLITICAL REPRESENTATION:
Highest representation: Rwanda (61.2%)
Lowest representation: Yemen (0.0%)
Average representation: 25.0%

🌍 AVERAGE GOVERNANCE SCORE BY CONTINENT:
Europe: 0.648
Americas: 0.564
Asia: 0.534
Africa: 0.511
Oceania: 0.397

In [56]:
# Correlation Analysis Between Features

print("=== FEATURE CORRELATION ANALYSIS ===\n")

# Select key numerical features for correlation
key_features = [
    'simplified_hdi', 'gdp_per_capita', 'life_expectancy', 'internet_pct',
    'education_normalized', 'democracy_score', 'press_freedom_score',
    'environmental_score', 'urbanization_rate', 'population_density'
]

# Create correlation matrix
correlation_matrix = df[key_features].corr()

print("🔍 CORRELATIONS WITH HUMAN DEVELOPMENT INDEX:")
hdi_correlations = correlation_matrix['simplified_hdi'].sort_values(ascending=False)
for feature, corr in hdi_correlations.items():
    if feature != 'simplified_hdi':
        print(f"{feature}: {corr:.3f}")

print(f"\n🔍 CORRELATIONS WITH GDP PER CAPITA:")
gdp_correlations = correlation_matrix['gdp_per_capita'].sort_values(ascending=False)
for feature, corr in gdp_correlations.items():
    if feature != 'gdp_per_capita':
        print(f"{feature}: {corr:.3f}")

print(f"\n🔍 STRONGEST CORRELATIONS (|r| > 0.7):")
strong_correlations = []
for i in range(len(correlation_matrix.columns)):
    for j in range(i+1, len(correlation_matrix.columns)):
        corr_value = correlation_matrix.iloc[i, j]
        if abs(corr_value) > 0.7:
            strong_correlations.append((correlation_matrix.columns[i], correlation_matrix.columns[j], corr_value))

for feat1, feat2, corr in strong_correlations:
    print(f"{feat1} ↔ {feat2}: {corr:.3f}")

=== FEATURE CORRELATION ANALYSIS ===

🔍 CORRELATIONS WITH HUMAN DEVELOPMENT INDEX:
internet_pct: 0.974
education_normalized: 0.974
life_expectancy: 0.880
gdp_per_capita: 0.659
urbanization_rate: 0.627
democracy_score: 0.409
population_density: 0.147
press_freedom_score: -0.393
environmental_score: -0.669

🔍 CORRELATIONS WITH GDP PER CAPITA:
simplified_hdi: 0.659
life_expectancy: 0.646
population_density: 0.550
education_normalized: 0.496
internet_pct: 0.496
urbanization_rate: 0.411
democracy_score: 0.200
environmental_score: -0.318
press_freedom_score: -0.360

🔍 STRONGEST CORRELATIONS (|r| > 0.7):
simplified_hdi ↔ life_expectancy: 0.880
simplified_hdi ↔ internet_pct: 0.974
simplified_hdi ↔ education_normalized: 0.974
life_expectancy ↔ internet_pct: 0.763
life_expectancy ↔ education_normalized: 0.763
internet_pct ↔ education_normalized: 1.000
democracy_score ↔ press_freedom_score: -0.721

In [57]:
# Interesting Country Comparisons and Rankings

print("=== INTERESTING COUNTRY COMPARISONS ===\n")

# Richest vs Poorest (by GDP per capita)
richest = df.loc[df['gdp_per_capita'].idxmax()]
poorest = df.loc[df['gdp_per_capita'].idxmin()]
print(f"💰 RICHEST vs POOREST (GDP per capita):")
print(f"Richest: {richest['country']} - ${richest['gdp_per_capita']:,.0f}")
print(f"Poorest: {poorest['country']} - ${poorest['gdp_per_capita']:,.0f}")
print(f"Ratio: {richest['gdp_per_capita'] / poorest['gdp_per_capita']:.0f}x")

# Healthiest vs Unhealthiest (by life expectancy)
healthiest = df.loc[df['life_expectancy'].idxmax()]
unhealthiest = df.loc[df['life_expectancy'].idxmin()]
print(f"\n🏥 HEALTHIEST vs UNHEALTHIEST (Life Expectancy):")
print(f"Healthiest: {healthiest['country']} - {healthiest['life_expectancy']:.1f} years")
print(f"Unhealthiest: {unhealthiest['country']} - {unhealthiest['life_expectancy']:.1f} years")
print(f"Difference: {healthiest['life_expectancy'] - unhealthiest['life_expectancy']:.1f} years")

# Most vs Least Connected (by internet)
most_connected = df.loc[df['internet_pct'].idxmax()]
least_connected = df.loc[df['internet_pct'].idxmin()]
print(f"\n🌐 MOST vs LEAST CONNECTED (Internet Access):")
print(f"Most connected: {most_connected['country']} - {most_connected['internet_pct']:.1f}%")
print(f"Least connected: {least_connected['country']} - {least_connected['internet_pct']:.1f}%")

# Most vs Least Urbanized
most_urban = df.loc[df['urbanization_rate'].idxmax()]
least_urban = df.loc[df['urbanization_rate'].idxmin()]
print(f"\n🏙️ MOST vs LEAST URBANIZED:")
print(f"Most urbanized: {most_urban['country']} - {most_urban['urbanization_rate']:.1f}%")
print(f"Least urbanized: {least_urban['country']} - {least_urban['urbanization_rate']:.1f}%")

# Best vs Worst Environmental Performance
best_enviro = df.loc[df['environmental_score'].idxmax()]
worst_enviro = df.loc[df['environmental_score'].idxmin()]
print(f"\n🌱 BEST vs WORST ENVIRONMENTAL PERFORMANCE:")
print(f"Best: {best_enviro['country']} - Score: {best_enviro['environmental_score']:.1f}")
print(f"Worst: {worst_enviro['country']} - Score: {worst_enviro['environmental_score']:.1f}")

=== INTERESTING COUNTRY COMPARISONS ===

💰 RICHEST vs POOREST (GDP per capita):
Richest: Monaco - $235,711
Poorest: Burundi - $238
Ratio: 989x

🏥 HEALTHIEST vs UNHEALTHIEST (Life Expectancy):
Healthiest: Switzerland - 84.0 years
Unhealthiest: Lesotho - 53.0 years
Difference: 31.0 years

🌐 MOST vs LEAST CONNECTED (Internet Access):
Most connected: Qatar - 100.0%
Least connected: Dem. People's Rep. Korea - 0.0%

🏙️ MOST vs LEAST URBANIZED:
Most urbanized: Singapore - 100.0%
Least urbanized: Papua New Guinea - 13.6%

🌱 BEST vs WORST ENVIRONMENTAL PERFORMANCE:
Best: Dem. Rep. Congo - Score: 97.7
Worst: Qatar - Score: 0.0

In [58]:
# Summary of Enhanced Data Extraction

print("=== ENHANCED DATA EXTRACTION SUMMARY ===\n")

print("🔧 NEW FEATURES CREATED:")

# Categorize new features
economic_features = ['gdp_per_capita', 'population_density', 'urbanization_rate', 'gender_ratio', 'dependency_ratio_proxy']
demographic_features = ['health_expenditure_per_capita', 'hospital_beds_per_1000', 'internet_score', 'press_freedom_score', 'life_expectancy_score', 'women_representation_score']
environmental_features = ['co2_per_capita', 'co2_intensity', 'renewable_energy_score', 'energy_self_sufficiency', 'environmental_score']
geographical_features = ['hemisphere', 'climate_zone', 'distance_from_equator', 'region_size']
development_features = ['simplified_hdi', 'development_level', 'governance_score', 'economic_stability']
composite_features = ['overall_development_score', 'quality_of_life_index', 'economic_power_index']

print(f"\n💰 ECONOMIC FEATURES ({len(economic_features)}):")
for feature in economic_features:
    print(f"  • {feature}")

print(f"\n👥 DEMOGRAPHIC FEATURES ({len(demographic_features)}):")
for feature in demographic_features:
    print(f"  • {feature}")

print(f"\n🌱 ENVIRONMENTAL FEATURES ({len(environmental_features)}):")
for feature in environmental_features:
    print(f"  • {feature}")

print(f"\n🗺️ GEOGRAPHICAL FEATURES ({len(geographical_features)}):")
for feature in geographical_features:
    print(f"  • {feature}")

print(f"\n📈 DEVELOPMENT FEATURES ({len(development_features)}):")
for feature in development_features:
    print(f"  • {feature}")

print(f"\n🏆 COMPOSITE INDICES ({len(composite_features)}):")
for feature in composite_features:
    print(f"  • {feature}")

print(f"\n📊 DATASET TRANSFORMATION:")
print(f"Original features: 64")
print(f"Enhanced features: {len(df.columns)}")
print(f"New features added: {len(df.columns) - 64}")
print(f"Total increase: {((len(df.columns) - 64) / 64 * 100):.1f}%")

print(f"\n🎯 KEY INSIGHTS ENABLED:")
print("• Comprehensive development analysis")
print("• Multi-dimensional country comparisons")
print("• Regional and continental patterns")
print("• Environmental performance tracking")
print("• Governance and democracy assessment")
print("• Economic and social development metrics")
print("• Correlation analysis between indicators")

print("\n✨ Enhanced data extraction complete! The dataset now provides rich, multi-dimensional analysis capabilities for global development studies.")

=== ENHANCED DATA EXTRACTION SUMMARY ===

🔧 NEW FEATURES CREATED:

💰 ECONOMIC FEATURES (5):
  • gdp_per_capita
  • population_density
  • urbanization_rate
  • gender_ratio
  • dependency_ratio_proxy

👥 DEMOGRAPHIC FEATURES (6):
  • health_expenditure_per_capita
  • hospital_beds_per_1000
  • internet_score
  • press_freedom_score
  • life_expectancy_score
  • women_representation_score

🌱 ENVIRONMENTAL FEATURES (5):
  • co2_per_capita
  • co2_intensity
  • renewable_energy_score
  • energy_self_sufficiency
  • environmental_score

🗺️ GEOGRAPHICAL FEATURES (4):
  • hemisphere
  • climate_zone
  • distance_from_equator
  • region_size

📈 DEVELOPMENT FEATURES (4):
  • simplified_hdi
  • development_level
  • governance_score
  • economic_stability

🏆 COMPOSITE INDICES (3):
  • overall_development_score
  • quality_of_life_index
  • economic_power_index

📊 DATASET TRANSFORMATION:
Original features: 64
Enhanced features: 94
New features added: 30
Total increase: 46.9%

🎯 KEY INSIGHTS ENABLED:
• Comprehensive development analysis
• Multi-dimensional country comparisons
• Regional and continental patterns
• Environmental performance tracking
• Governance and democracy assessment
• Economic and social development metrics
• Correlation analysis between indicators

✨ Enhanced data extraction complete! The dataset now provides rich, multi-dimensional analysis capabilities for global development studies.